name = "sweet-raw"
display-name = "Sweet Raw"
description = "Dark theme inspired on Sweet Theme"
version = "0.0.7"
author = "felipetesc"
repository = "felipetesc/lapce-sweetraw-theme"
themes = ["sweet-raw-theme.toml"]
