name = "sweet-raw"
display-name = "Sweet Raw"
description = "Theme inspired on Sweet Theme"
version = "0.0.1"
author = "felipetesc"
repository = "felipetesc/lapce-sweetraw-theme"
themes = ["aleph.toml"]
