[theme]
name = "Sweet Raw"

[color-theme.base]
white = "#ABB2BF"
black = "#0C0E14"
grey = "#3E4451"
blue = "#02BFE3"
red = "#FC433C"
yellow = "#FDCE19"
orange = "#D19A66"
green = "#03E6C7"
purple = "#A607E5"
cyan = "#56B6C2"
magenta = "#C678DD"

[color-theme.syntax]
attribute = "$white"
builtinType = "$white"
comment = "#ABB2BF"
constant = "#00C1E3"
constructor = "#00C1E3"
embedded = "$white"
enum = "$white"
enum-member = "$white"
enumMember = "$white"
escape = "$white"
field = "#3193D7"
function = "#FD454C"
"function.method" = "#FD454C"
interface = "$white"
keyword = "#FD4A85"
"keyword.control" = "$white"
method = "#FD454C"
number = "$white"
property = "$white"
"punctuation.delimiter" = "$white"
selfKeyword = "$white"
string = "#03E5C4"
"string.escape" = "#03E5C4"
struct = "#00C1E3"
structure = "#00C1E3"
symbol = "#C34EF6"
tag = "#C34EF6"
"text.reference" = "#03E5C4"
"text.title" = "#03E5C4"
"text.uri" = "#03E5C4"
type = "#FD4A85"
"type.builtin" = "#FD4A85"
typeAlias = "#FD4A85"
variable = "#C34EF6"
"variable.other.member" = "$white"

[color-theme.ui]
"activity.background" = "$black"
"activity.current" = "$black"
"completion.background" = "$black"
"completion.current" = "#2C313A"
"editor.background" = "$black"
"editor.caret" = "#FD4A85"
"editor.current_line" = "#2C313C"
"editor.dim" = "#5C6370"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.indent_guide" = "#212435"
"editor.link" = "#E9447B"
"editor.selection" = "$grey"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "#212435"
"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#212435"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#161925"
"inlay_hint.background" = "#161925"
"inlay_hint.foreground" = "$white"
"lapce.border" = "#161925"
"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "#FD454C"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"
"lapce.plugin.author" = "#B0B0B0"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "#DDDDDD"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "#C18401"
"lapce.remote.disconnected" = "#E45649"
"lapce.remote.local" = "#E9447B"
"lapce.scroll_bar" = "#8549E5"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#E9447B"
"lapce.tab.inactive.background" = "$black"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#DF8FE9"
"lapce.tab.separator" = ""
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "#21252B"
"palette.current.background" = "#2C313A"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"
"panel.background" = "$black"
"panel.current.background" = "#2C313A"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#5C6370"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#5C6370"
"panel.hovered.background" = "#343A45"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C6370"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "$black"
"status.foreground" = "$white"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
trim-search-results-whitespace = true
