
[theme]
name = "Sweet Raw"

[ui]
font-family = "Roboto"
font-size = 14
status-height = 30
tab-min-width = 120
drop-shadow-width = 1
header-height = 40
scroll-width = 10
scroll-width = 15


[terminal]
font-family = "Roboto"
font-size = 14
line-height = 22
shell = "bash"

[theme.base]
white = "#ABB2BF"
black = "#282C34"
grey = "#3E4451"
blue = "#61AFEF"
red = "#E06C75"
yellow = "#E5C07B"
orange = "#D19A66"
green = "#98C379"
purple = "#C678DD"
cyan = "#56B6C2"
magenta = "#C678DD"

[theme.syntax]
"comment" = "#5C6370"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$blue"
"method" = "$blue"
"function.method" = "$blue"
"keyword" = "$purple"
"selfKeyword" = "$purple"
"field" = "$red"
"property" = "$red"
"enumMember" = "$red"
"enum-member" = "$red"
"variable.other.member" = "$red"
"string" = "$green"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"

[theme.ui]
"activity.background" = "#181b28"
"completion.background" = "#181b28"
"editor.background" = "#181b28"
"lapce.border" = "#10121f"
"lapce.dropdown_shadow" = "#10121f"
"panel.background" = "#171926"
"status.background" = "#10121f"
"terminal.background" = "#10121f"
"lapce.active_tab" = "#10121f"
"activity.current" = "#181b28"
"editor.focus" = "#c50ed2"
"palette.background" = "#0c0e14"
"palette.current" = "#202d40"

[editor]
font-family = "Roboto"
font-size = 14
tab-width = 5
